### ISSUE TITLE
[Recover backup] Jump to next word on Keyboard return

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#136]
App version: v0.1.91

When entering the seed words,
If I select the world from suggestion popup, the focus goes to next word automatically, which is good.

Same can happen when I press return key in the keyboard. Right now it closes the keyboard.

![Recover backup - 12 words 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/015db3b5-5b5c-4ef8-85ab-2ed6b0fe2a5b)

**Comment by i5hi** [comment]
@mocodesmo The enter button now cancels the word, rather than selecting the word in the list. 

Enter should select the highlighted word.

If three words are left and they press enter, it will select the first word.

If one work is left, it will select the only word left. 


It is intuitive to press the enter button after typing the whole word and assume your entry will be selected. 

If you no words in the list exist when you press enter, then it can remove the entry.

**Comment by i5hi** [comment]
@mocodesmo currently it selects the word but the drop down remains.

Drop down should dissapear and focus should be on the next input field.

**Comment by mocodesmo** [comment]
fixed on main yesterday @i5hi
