### ISSUE TITLE
Wallet selection bugs

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#183]
App version: v0.1.95/Mainnet

- [ ] P1: Unexpected wallet removal removal from UI, when deleting some other wallet.

### P1: Steps to reproduce:
1. I had 3 wallets.
2. Navigated to settings of first 2 wallets and back to home.
3. Opened 3rd wallet. Clicked on backup.
4. Pressed H/w back button to close the Best practices popup.
5. Wallet settings page is shown as expected.
6. Now clicked 'Delete wallet` and confimed the popup.

Expected:
App navigate back to home screen, listing first two wallets.

Observed:
1. App navigated back to home screen, listing only the first wallet.
2. The second wallet is not actually deleted, but only is hidden from the UI.
3. Because when I try to restore it again, I get Wallet exists error.
4. I close the app and re-open it again, 2 wallets are now displayed.

Screen recording with voice over
https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/8d29484a-f227-489d-ad58-a4c637bc8233

**Comment by i5hi** [comment]
@saiy2k when you opened the 3rd wallet you clicked on the edge of the card where the page transitions, right?

@mocodesmo consider this while you try to reproduce. 

I have tried just normally deleting a 1/3 wallets and this does not happen but consitently happens when i select a wallet by clicking the edge of its card while it is NOT in focus. Strange thing is that it opens up as the wallet you would expect, removes itself entirely as expected but also removes the wallet that was in focus from the HomeCubit.

**Comment by saiy2k** [comment]
This is fixed now. Tested
1. both in mainnet and testnet. 
2. By tapping on left/right edges.
