### ISSUE TITLE
Can't change network 

### ISSUE THREAD

**Issue by JuanOfTheNorth** [SatoshiPortal/bullbitcoin-mobile#304]
New version 0.2.1-4

Was in this app a few days ago, and i'm pretty sure the last thing i did was on testnet. 

Just downloaded new version and don't see the option to change network back to main net. 

Guess I might have to recover from seed.

**Comment by i5hi** [comment]
Hey @JuanOfTheNorth We temporarily removed testnet because things were very unstable. We will bring it back once we move to our setup to testnet4. 

We removed the button to toggle networks and didnt realize this would be a problem for users who are currently on testnet and want to return to mainnet. 

Let us know if you have already reinstalled and recovered, if not and you would prefer we can push a patch that will update in a few hours.

**Comment by i5hi** [comment]
Pushing a patch shortly.

**Comment by JuanOfTheNorth** [comment]
Resolved in v0.2.1-5

Thank you

**Comment by i5hi** [comment]
Once you move to mainnet, you wont be able to go back to testnet, but your testnet seed is in secure storage and as soon as we get testnet4 supported we will bring it back. Testnet3 is really buggy at the moment.
