### ISSUE TITLE
[Send] When using an LNURL string, recognize and show a better error

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#313]
Since we dont currently support LNURL and this is a format used by bullbitcoin.com we should recognize its use and give a better error.

We wont ever be able to support Lnurl-W but Lnurl-P maybe possible?

**Comment by michael1011** [comment]
Both, LNURL pay and LNURL withdraw, can be supported

## LNURL pay LUD-06

Reference: https://github.com/lnurl/luds/blob/luds/06.md

Can be implemented by:

1. Fetching an invoice for the desired amount on the client from the LNURL sever
2. Creating a swap with that invoice

### Implementation notes:

[Lightning Addresses](https://github.com/andrerfneves/lightning-address/blob/master/README.md#tldr) should also be implemented. They are very similar to LUD-06. The only difference being that instead of decoding the LNURL string, a REST API call is being done.

## LNURL withdraw LUD-03

Reference: https://github.com/lnurl/luds/blob/luds/03.md

Can be implemented by:

1. Create a reverse swap with the desired amount
2. Giving that invoice to the LNURL server
